#!/usr/bin/env python3
"""Rebuilds UTEX 2973 in isolation and checks byte identity.

The builder intentionally refreshes ``meta.json.builtAt``. This checker replaces
only that field with the published value before comparing exact bytes; every
other generated byte must match the established release.
"""

from __future__ import annotations

import hashlib
import json
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_features import build  # noqa: E402
from organisms import get_organism  # noqa: E402


def digest(content: bytes) -> str:
    """Returns one complete lower-case SHA-256 digest."""
    return hashlib.sha256(content).hexdigest()


def normalized_meta(candidate: bytes, published: bytes) -> bytes:
    """Returns candidate meta with only the published build timestamp restored."""
    candidate_document = json.loads(candidate)
    published_document = json.loads(published)
    candidate_document["builtAt"] = published_document["builtAt"]
    return (
        json.dumps(candidate_document, separators=(",", ":"), ensure_ascii=False).encode()
        + b"\n"
    )


def main() -> int:
    """Runs the isolated rebuild and reports exact per-file digests."""
    organism = get_organism("utex2973")
    published_dir = organism.path("outputDirectory")
    with tempfile.TemporaryDirectory() as temporary:
        rebuilt_dir = Path(temporary)
        build(
            organism.path("rawDirectory"),
            rebuilt_dir,
            organism.path("annotationDirectory"),
            organism,
        )
        failures = []
        for rebuilt_path in sorted(rebuilt_dir.glob("*.json")):
            published_path = published_dir / rebuilt_path.name
            candidate = rebuilt_path.read_bytes()
            published = published_path.read_bytes()
            if rebuilt_path.name == "meta.json":
                candidate = normalized_meta(candidate, published)
            matches = candidate == published
            print(
                f"{'PASS' if matches else 'FAIL'} {rebuilt_path.name} "
                f"published={digest(published)} rebuilt={digest(candidate)}"
            )
            if not matches:
                failures.append(rebuilt_path.name)
    if failures:
        print("different after builtAt normalization: " + ", ".join(failures))
        return 1
    print("UTEX 2973 base build is byte-identical; meta.builtAt was the only normalization")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
