#!/usr/bin/env python3
"""Write a human review sheet for dataset pairs from a pair-comparability table.

The input is the pair table returned by the comparability scoring: one row per
pair, with each side's condition set, one screen result per axis, and a verdict.
The sheet lays the two sides of each selected pair next to each other, axis by
axis, and leaves the judgement cells empty. It decides nothing.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Iterable, Sequence

AXES = (
    "temperature",
    "light_intensity",
    "light_regime",
    "co2",
    "medium",
    "culture_format_and_phase",
)
"""Axis columns of the pair table, in display order."""

_CONDITION_SET = re.compile(r"^row (\d+) \[(.*?)\] (.*)$", re.DOTALL)


def parse_condition_set(cell: str) -> tuple[int, str, dict[str, str]]:
    """Split a condition-set cell into its source row, label, and axis values.

    Args:
        cell: A cell of the form ``row N [label] axis=value ;; axis=value``.

    Returns:
        The source table's data-row number, the condition-set label, and the
        values keyed by axis name exactly as the cell names them.

    Raises:
        ValueError: If the cell does not have that form.
    """
    match = _CONDITION_SET.match(cell)
    if match is None:
        raise ValueError(f"not a condition-set cell: {cell[:60]!r}")
    values: dict[str, str] = {}
    for part in match.group(3).split(" ;; "):
        key, _, value = part.partition("=")
        values[key.strip()] = value.strip()
    return int(match.group(1)), match.group(2), values


def select_pairs(rows: Iterable[dict[str, str]], verdict: str) -> list[dict[str, str]]:
    """Return the rows with the given verdict, most axes passed first."""
    chosen = [row for row in rows if row["verdict"].split(" ")[0] == verdict]
    return sorted(
        chosen,
        key=lambda row: (-_axes_passed(row), row["artifact_a"], row["artifact_b"]),
    )


def _axes_passed(row: dict[str, str]) -> int:
    """Read the leading count of an ``N of 6`` cell."""
    return int(row["axes_passed"].split(" ")[0])


def _cell(text: str) -> str:
    """Make a value safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ") or "—"


def render_pair(number: int, row: dict[str, str]) -> str:
    """Render one pair as a Markdown section with an empty judgement block."""
    row_a, label_a, values_a = parse_condition_set(row["condition_set_a"])
    row_b, label_b, values_b = parse_condition_set(row["condition_set_b"])
    lines = [
        f"## {number}. {row['artifact_a']} against {row['artifact_b']}",
        "",
        f"- **Data type:** {row['data_type']}",
        f"- **Screen verdict:** {row['verdict']}; {row['axes_passed']} axes passed; "
        f"marginal axis: {row['failing_or_marginal_axis']}",
        f"- **A:** condition table row {row_a}, {label_a}",
        f"- **B:** condition table row {row_b}, {label_b}",
        "",
        "| Axis | A | B | Screen result |",
        "| --- | --- | --- | --- |",
    ]
    for axis in AXES:
        # The table names one combined axis; the condition sets carry its two parts.
        keys = ("culture_format", "growth_phase") if axis == AXES[-1] else (axis,)
        side_a = "; ".join(values_a.get(key, "") for key in keys).strip("; ")
        side_b = "; ".join(values_b.get(key, "") for key in keys).strip("; ")
        lines.append(
            f"| {axis} | {_cell(side_a)} | {_cell(side_b)} | {_cell(row[axis])} |"
        )
    lines += [
        "",
        "- **Judgement** (may share a layer / keep separate / don't know yet):",
        "- **Reviewer and date:**",
        "- **Basis:**",
        "",
    ]
    return "\n".join(lines)


def render_sheet(rows: Sequence[dict[str, str]], verdict: str, source: str) -> str:
    """Render the whole sheet for every pair with the given verdict."""
    pairs = select_pairs(rows, verdict)
    head = [
        f"# Pair review sheet: {len(pairs)} pairs with verdict \"{verdict}\"",
        "",
        f"Generated by `tools/pair_review_sheet.py` from `{source}`. Each value is",
        "verbatim from the condition table row named beside it. The screen result is",
        "the scoring's reading against the default thresholds; it is evidence, not a",
        "decision. Fill the three lines under each pair. Pairs are ordered by the",
        "number of axes passed.",
        "",
    ]
    body = [render_pair(number, row) for number, row in enumerate(pairs, start=1)]
    return "\n".join(head + body)


def main(argv: Sequence[str] | None = None) -> int:
    """Read the pair table and write the review sheet."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("pairs", type=Path, help="pair table, tab-separated")
    parser.add_argument("output", type=Path, help="Markdown sheet to write")
    parser.add_argument("--verdict", default="escalate", help="verdict to select")
    args = parser.parse_args(argv)
    csv.field_size_limit(sys.maxsize)
    with args.pairs.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    args.output.write_text(
        render_sheet(rows, args.verdict, args.pairs.name), encoding="utf-8"
    )
    print(f"wrote {len(select_pairs(rows, args.verdict))} pairs to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
